/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model.glb --transform 
Files: public/model.glb [52.59MB] > D:\Freelance\apex-config\model-transformed.glb [1.42MB] (97%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/model-transformed.glb");
  return (
    <group
      scale={0.005}
      position={[0, 0.5, 0]}
      rotation={[-1.6, 0, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Shaft_Shovel_003.geometry}
        material={materials.Shaft_Chrome}
      />
      <mesh
        geometry={nodes.Hydraulic_Cylinder_Tube_004.geometry}
        material={materials.Connectors_Chrome}
      />
      <mesh
        geometry={nodes.Hydraulic_Cylinder_Tube001.geometry}
        material={materials.Window_s_Rubber}
      />
      <mesh
        geometry={nodes.Hydraulic_Cylinder_Cover_002.geometry}
        material={materials.Hydraulic_Cylinder_Black_Paint}
      />
      <mesh
        geometry={nodes.Stand001.geometry}
        material={materials.back_light}
      />
      <mesh
        geometry={nodes.Back_LightBulb001.geometry}
        material={materials.back_light_1}
      />
      <mesh
        geometry={nodes.Levers_Plast001.geometry}
        material={materials.Black_Plast}
      />
      <mesh
        geometry={nodes.Levers001.geometry}
        material={materials.Bottom_Black_Met}
      />
      <mesh
        geometry={nodes.Front_Door_Bolts001.geometry}
        material={materials.Track_Mechanism_Black_Met}
      />
      <mesh
        geometry={nodes.Interior_Details001.geometry}
        material={materials.Cab_Interior}
      />
      <mesh
        geometry={nodes.Headlight001.geometry}
        material={materials.Headlight_Glass}
      />
      <mesh
        geometry={nodes.Back_Light_White001.geometry}
        material={materials.Back_Light_Glass}
      />
      <mesh
        geometry={nodes.Wiper001.geometry}
        material={materials.Cab_Black_Met}
      />
      <mesh
        geometry={nodes.Back_Wheel_Left001.geometry}
        material={materials.Wheels_Black_Met}
      />
      <mesh
        geometry={nodes.Back_Glass001.geometry}
        material={materials.Glass}
      />
      <mesh
        geometry={nodes.Bumper001.geometry}
        material={materials.Bumper_Black_Met}
      />
      <mesh
        geometry={nodes.Hood_Cover001.geometry}
        material={materials.Hood_Cover_Red}
      />
      <mesh
        geometry={nodes.Bottom_Body001.geometry}
        material={materials.Body_Bottom}
      />
      <mesh geometry={nodes.Black_Box001.geometry} material={materials.Black} />
      <mesh
        geometry={nodes.Body_Side001.geometry}
        material={materials.Body_Side}
      />
      <mesh
        geometry={nodes.Dipper_Stick001.geometry}
        material={materials.Body_Dipper_Stick}
      />
      <mesh
        geometry={nodes.Track_Right_151.geometry}
        material={materials.Tracks_Rubber}
      />
      <mesh
        geometry={nodes.Shovel001.geometry}
        material={materials.Shovel_Black_Met}
      />
    </group>
  );
}

useGLTF.preload("/model-transformed.glb");
