/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 A320MM.glb --transform 
Files: A320MM.glb [95.51MB] > D:\Freelance\apex-config\public\A320MM-transformed.glb [4.94MB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/A320MM-transformed.glb");
  //console that this model is rendered
  console.log("A320MM model is rendered");
  if (materials.R_ubber_gray.rubber) {
    materials.R_ubber_gray.roughness = 0.9; // Set roughness to 0.5
    materials.R_ubber_gray.metalness = 0.7; // Set metalness to 0.5
  }
  return (
    <group
      scale={[3, 3, 2.2 * 1.2]}
      rotation={[Math.PI / 2, Math.PI, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        position={[12, 0, 27]}
        geometry={nodes.Box001.geometry}
        material={materials.R_ubber_gray}
      />
      <mesh
        position={[12, 0, -27]}
        geometry={nodes.Box001.geometry}
        material={materials.R_ubber_gray}
      />
    </group>
  );
}

useGLTF.preload("/A320MM-transformed.glb");
