/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 A400MM.glb --transform 
Files: A400MM.glb [95.51MB] > D:\Freelance\apex-config\public\A400MM-transformed.glb [4.96MB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/A400MM-transformed.glb");
  //console that this model is rendered
  console.log("A400MM model is rendered");
  return (
    <group
      scale={[3, 3, 2.2 * 1.2]}
      rotation={[Math.PI / 2, Math.PI, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        position={[12, 0, 28]}
        geometry={nodes.Box134.geometry}
        material={materials.R_ubber_gray}
      />
      <mesh
        position={[12, 0, -28]}
        geometry={nodes.Box134.geometry}
        material={materials.R_ubber_gray}
      />
    </group>
  );
}

useGLTF.preload("/A400MM-transformed.glb");
