/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 A450MM.glb --transform 
Files: A450MM.glb [95.51MB] > D:\Freelance\apex-config\public\A450MM-transformed.glb [4.98MB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/A450MM-transformed.glb");
  //console that this model is rendered
  console.log("A450MM model is rendered");
  if (materials.R_ubber_gray.rubber) {
    materials.R_ubber_gray.roughness = 0.9; // Set roughness to 0.5
    materials.R_ubber_gray.metalness = 0.7; // Set metalness to 0.5
  }
  return (
    <group
      {...props}
      dispose={null}
      scale={[3, 3, 2.2 * 1.2]}
      rotation={[Math.PI / 2, Math.PI, 0]}
    >
      <mesh
        position={[12, 0, 29]}
        geometry={nodes.Box137.geometry}
        material={materials.R_ubber_gray}
      />
      <mesh
        position={[12, 0, -29]}
        geometry={nodes.Box137.geometry}
        material={materials.R_ubber_gray}
      />
    </group>
  );
}

useGLTF.preload("/A450MM-transformed.glb");
