/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 B400MM.glb --transform 
Files: B400MM.glb [12.99MB] > D:\Freelance\apex-config\public\B400MM-transformed.glb [840.38KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/B400MM-transformed.glb");
  //console that this model is rendered
  console.log("B400MM model is rendered");
  if (materials.rubber) {
    materials.rubber.roughness = 0.9; // Set roughness to 0.5
    materials.rubber.metalness = 0.7; // Set metalness to 0.5
  }

  return (
    <group
      scale={[3, 3, 2.2 * 1.2]}
      rotation={[Math.PI / 2, Math.PI, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        position={[12, 0, 28]}
        geometry={nodes.Rubber_Track.geometry}
        material={materials.rubber}
      />
      <mesh
        position={[12, 0, -28]}
        geometry={nodes.Rubber_Track.geometry}
        material={materials.rubber}
      />
    </group>
  );
}

useGLTF.preload("/B400MM-transformed.glb");
