/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 B450MM.glb --transform 
Files: B450MM.glb [12.99MB] > D:\Freelance\apex-config\public\B450MM-transformed.glb [844.62KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/B450MM-transformed.glb");
  //console that this model is rendered
  console.log("B450MM model is rendered");
  return (
    <group
      scale={[3, 3, 2.2]}
      rotation={[Math.PI / 2, Math.PI, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        position={[12, 0, 30]}
        geometry={nodes.Rubber_Track001.geometry}
        material={materials.rubber}
      />
      <mesh
        position={[12, 0, -30]}
        geometry={nodes.Rubber_Track001.geometry}
        material={materials.rubber}
      />
    </group>
  );
}

useGLTF.preload("/B450MM-transformed.glb");
